apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-login-app-deployment
  labels:
    app: boot-login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boot-login-app
  template:
    metadata:
      labels:
        app: boot-login-app
    spec:
      containers:
        - name: boot-login-app
          image: bluedio/boot-login-app:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
