apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boot-login-app
  template:
    metadata:
      labels:
        app: boot-login-app
    spec:
      containers:
        - name: boot-login-app
          image: bluedio/boot-login-app:v1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "dpg-d44fudadbo4c73et8vi0-a.oregon-postgres.render.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "mydb_5moa"
            - name: DB_USERNAME
              value: "mydb_5moa_user"
            - name: DB_PASSWORD
              value: "mJ4N0sXGa0e4A6ynkqHMOoBGu5vHFTTW"
