apiVersion: v1
kind: Service
metadata:
  name: boot-login-app-service
spec:
  selector:
    app: boot-login-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
